-- Basil baseline schema.
-- Conventions: snake_case names; ids from identity columns or sequences; times are timestamptz in UTC;
-- MD5 as lowercase hex text.

create extension if not exists pg_trgm;

create table users
(
	id          integer generated by default as identity primary key check (id >= 1),
	name        text        not null,
	safe_name   text        not null unique,
	country     integer     not null,
	permissions bigint      not null,
	deleted_at  timestamptz null
) with (fillfactor = 90);

-- Partial-name search; kept only if measured useful.
create index users_safe_name_trgm on users using gin (safe_name gin_trgm_ops);

create table credentials
(
	user_id       integer primary key references users (id),
	password_hash text not null
);

create table logins
(
	id                    bigint primary key,
	user_id               integer     not null references users (id),
	ip                    inet        not null,
	timestamp             timestamptz not null,
	client_date           text        null,
	client_revision       integer     null,
	client_stream         integer     null,
	osu_path_hash         text        null,
	network_adapters      text        null,
	network_adapters_hash text        null,
	uninstall_hash        text        null,
	disk_signature_hash   text        null
);

create index logins_user_id_timestamp on logins (user_id, timestamp desc);

create table restrictions
(
	id          integer generated by default as identity primary key check (id >= 1),
	user_id     integer     not null references users (id),
	permissions bigint      not null,
	starts_at   timestamptz not null,
	ends_at     timestamptz null
);

create index restrictions_user_id on restrictions (user_id);

create table relationships
(
	actor_id   integer     not null references users (id),
	target_id  integer     not null references users (id),
	type       integer     not null,
	created_at timestamptz not null,
	primary key (actor_id, target_id)
);

create table channels
(
	name              text primary key,
	topic             text    not null,
	read_permissions  bigint  not null,
	write_permissions bigint  not null,
	auto_join         boolean not null,
	visible           boolean not null
);

insert into channels (name, topic, read_permissions, write_permissions, auto_join, visible)
values ('#osu', 'General discussion.', 0, 0, true, true),
	   ('#lobby', 'Multiplayer lobby discussion.', 0, 0, false, true);

create table settings --TODO: Transpose this
(
	id                       integer primary key check (id = 1),
	motd                     text    null,
	locked_creation          integer not null,
	menu_icon_url            text    null,
	menu_icon_image          text    null,
	mirror_download_endpoint text    null,
	mirror_search_endpoint   text    null
);

-- 4 = CreationLocks.Beatmapsets.
insert into settings (id, motd, locked_creation, menu_icon_url, menu_icon_image, mirror_download_endpoint,
					  mirror_search_endpoint)
values (1, null, 4, null, null, null, null);

create table menu_banners
(
	image      text primary key,
	url        text        not null,
	starts_at  timestamptz null,
	ends_at    timestamptz null,
	created_at timestamptz not null
);

create table beatmapsets
(
	id         integer primary key check (id >= 1),
	artist     text        not null,
	title      text        not null,
	creator    text        not null,
	created_at timestamptz not null,
	updated_at timestamptz not null,
	locked     boolean     not null,
	visible    boolean     not null
);

-- Sequence for local beatmapset IDs. Start value equals Beatmapset.LocalIdFloor in Domain.
create
	sequence local_beatmapset_ids as integer start with 1000000000;

-- objects is the JSON of a Basil.Domain.Beatmaps.BeatmapObjects value; length is in milliseconds.
create table beatmaps
(
	id            integer primary key check (id >= 1),
	beatmapset_id integer          not null references beatmapsets (id) on delete cascade,
	hash          text             not null unique,
	version       text             not null,
	mode          integer          not null,
	star          double precision not null,
	length        integer          not null,
	bpm           double precision not null,
	cs            double precision not null,
	ar            double precision not null,
	od            double precision not null,
	hp            double precision not null,
	objects       jsonb            not null,
	locked        boolean          not null,
	visible       boolean          not null
);

-- Sequence for local beatmap IDs. Start value equals Beatmap.LocalIdFloor in Domain.
create
	sequence local_beatmap_ids as integer start with 1000000000;

create index beatmaps_beatmapset_id on beatmaps (beatmapset_id);
create index beatmaps_mode on beatmaps (mode);

create table matches
(
	id         integer generated by default as identity primary key check (id >= 1),
	name       text        not null,
	creator_id integer     null references users (id),
	started_at timestamptz not null,
	ended_at   timestamptz null,
	is_private boolean     not null
) with (fillfactor = 90);

create index matches_ended_at on matches (ended_at);

create table rounds
(
	match_id      integer     not null references matches (id),
	number        integer     not null,
	beatmap_hash  text        not null,
	mode          integer     not null,
	mods          integer     not null,
	freemods      boolean     not null,
	team_type     integer     not null,
	win_condition integer     not null,
	seed          integer     not null,
	started_at    timestamptz not null,
	ended_at      timestamptz null,
	aborted       boolean     not null,
	primary key (match_id, number)
) with (fillfactor = 90);

create table match_events
(
	id        bigint primary key,
	match_id  integer     not null references matches (id),
	type      integer     not null,
	timestamp timestamptz not null,
	actor_id  integer     null references users (id),
	target_id integer     null references users (id),
	detail    text        null
);

create index match_events_match_id on match_events (match_id);

create table scores
(
	id            integer generated by default as identity primary key check (id >= 1),
	user_id       integer     null references users (id),
	beatmap_hash  text        null,
	mode          integer     not null,
	mods          integer     not null,
	num300        integer     not null,
	num100        integer     not null,
	num50         integer     not null,
	num_geki      integer     not null,
	num_katu      integer     not null,
	num_miss      integer     not null,
	total_score   integer     not null,
	max_combo     integer     not null,
	current_combo integer     not null,
	grade         integer     not null,
	is_passed     boolean     not null,
	is_full_combo boolean     not null,
	timestamp     timestamptz not null,
	checksum      text        null unique
);

create index scores_user_id on scores (user_id);
create index scores_beatmap_hash on scores (beatmap_hash);

create table round_scores
(
	score_id     integer primary key references scores (id),
	match_id     integer not null,
	round_number integer not null,
	team         integer null
);

create index round_scores_match_id_round_number on round_scores (match_id, round_number);

create table user_stats
(
	user_id      integer not null references users (id),
	mode         integer not null,
	total_score  bigint  not null,
	ranked_score bigint  not null,
	play_count   integer not null,
	primary key (user_id, mode)
) with (fillfactor = 90);
