services:
  basil:
    build: .
    ports:
      - "443:443" # HTTPS
      - "6667:6667" # IRC no TLS
    volumes:
      - ./docker-data/Data:/app/Data
      - ./docker-data/Logs:/app/Logs
      - ./src/Basil.Web/Data/appsettings.json:/app/Data/appsettings.json:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: unless-stopped
