name: basil

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: basil
      MYSQL_PASSWORD: basil
      MYSQL_DATABASE: basil
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - basil-mysql-data:/var/lib/mysql
    healthcheck:
      test: '/usr/bin/mysql --user=basil --password=basil --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - basil-redis-data:/data

volumes:
  basil-mysql-data:
  basil-redis-data:
