<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Basil.Application\Basil.Application.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Persistence\Migrations\*.sql"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next"/>
		<PackageReference Include="BouncyCastle.Cryptography"/>
		<PackageReference Include="Dapper"/>
		<PackageReference Include="dbup-sqlite"/>
		<PackageReference Include="Microsoft.Data.Sqlite"/>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory"/>
		<PackageReference Include="Microsoft.Extensions.Http"/>
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder"/>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
		<PackageReference Include="ppy.osu.Game.Rulesets.Osu"/>
		<PackageReference Include="ppy.osu.Game.Rulesets.Taiko"/>
		<PackageReference Include="ppy.osu.Game.Rulesets.Catch"/>
		<PackageReference Include="ppy.osu.Game.Rulesets.Mania"/>
	</ItemGroup>

</Project>
