<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Basil.Domain\Basil.Domain.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Basil.Application.Services" />
	</ItemGroup>
</Project>