using Basil.Infrastructure.Security;

namespace Basil.Infrastructure.Tests.Security;

/// <summary>
///     Ciphertext generated by actually running bancho.py's app/encryption.py:encrypt_score_aes_data
///     (via py3rijndael) — not hand-derived — so this test catches a mismatch against the real
///     client-facing protocol, not just internal self-consistency.
/// </summary>
public class RijndaelScoreDecryptorTests
{
    private const string IvBase64 = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=";
    private const string OsuVersion = "20210520";

    private const string ScoreDataBase64 =
        "fRJr4+syKqvnOK9Ks3RmOB9DDqqahqqB166HvYITNF/jny83NYRL+h0SRtXc2i048oJwyp0SVOTouXBfyyRbUhbcXz5YSxroTujOgv+VyaCoVR755MA6H5g1Zc0jePRd";

    private const string ClientHashBase64 = "V0evq1wNLPakUmrnrOvpLElNYkZ+r1I7y4UNe6XKLvA=";

    [Fact]
    public void Decrypt_MatchesPythonEncryptionOracle()
    {
        var decryptor = new RijndaelScoreDecryptor();

        var (fields, clientHash) = decryptor.Decrypt(ScoreDataBase64, ClientHashBase64, IvBase64, OsuVersion);

        Assert.Equal(
            [
                "abc123checksum", "490", "5", "3", "0", "0", "1", "12345678", "500", "False", "S", "72", "True", "0",
                "210520235959", "20210520 "
            ],
            fields);
        Assert.Equal("client_hash_plaintext_value", clientHash);
    }
}