<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App"/>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.AspNetCore.Builder"/>
		<Using Include="Microsoft.AspNetCore.Http"/>
		<Using Include="Microsoft.AspNetCore.Routing"/>
		<Using Include="Microsoft.Extensions.DependencyInjection"/>
		<Using Include="Microsoft.Extensions.Hosting"/>
		<Using Include="Microsoft.Extensions.Logging"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
		<PackageReference Include="Microsoft.OpenApi"/>
		<PackageReference Include="Scalar.AspNetCore"/>
		<PackageReference Include="SixLabors.ImageSharp.Web"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Application\Services\Basil.Application.Services.Contracts\Basil.Application.Services.Contracts.csproj"/>
		<ProjectReference Include="..\..\Application\Services\Basil.Application.Services.Implementations\Basil.Application.Services.Implementations.csproj"/>
		<ProjectReference Include="..\..\Basil.Infrastructure\Basil.Infrastructure.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Basil.Host.Api.Tests"/>
	</ItemGroup>

</Project>
