using Basil.Server.Shared.Persistence;
using Basil.Server.Features.Users;
using Basil.Domain.Login;
using Basil.Domain.Users;
using Dapper;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Logging;

namespace Basil.Server.Features.Users;

/// <inheritdoc cref="IUserRepository" />
/// <remarks>
///     Rows map through the private mutable <c>UserRow</c> DTO. Each method opens its own
///     connection.
/// </remarks>
public sealed class SqliteUserRepository(string connectionString, ILogger<SqliteUserRepository> logger)
	: IUserRepository
{
	/// <inheritdoc />
	public async Task<User?> FetchByIdAsync(int id, CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		var row = await connection.QuerySingleOrDefaultAsync<UserRow>(
			"SELECT * FROM Users WHERE Id = @Id",
			new { Id = id });
		return row?.ToUser();
	}

	/// <inheritdoc />
	/// <remarks>
	///     The lookup is against the <c>SafeName</c> column, which the database generates using the
	///     same rule as <see cref="User.MakeSafeName" />, so a name matches regardless of case or
	///     spaces.
	/// </remarks>
	public async Task<User?> FetchByNameAsync(string name, CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		var row = await connection.QuerySingleOrDefaultAsync<UserRow>(
			"SELECT * FROM Users WHERE SafeName = @SafeName",
			new { SafeName = User.MakeSafeName(name) });
		return row?.ToUser();
	}

	/// <inheritdoc />
	public async Task<string?> FetchPasswordHashAsync(int id, CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		return await connection.QuerySingleOrDefaultAsync<string>(
			"SELECT PwBcrypt FROM Users WHERE Id = @Id",
			new { Id = id });
	}

	/// <inheritdoc />
	/// <remarks>
	///     The country is stored as its two-letter acronym, produced by the
	///     <c>Country.ToAcronym()</c> extension.
	/// </remarks>
	public async Task UpdateCountryAsync(int id, Country country, CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		await connection.ExecuteAsync(
			"UPDATE Users SET Country = @Country WHERE Id = @Id",
			new { Id = id, Country = country.ToAcronym() });
		logger.LogDebug("User row updated: Id={Id} Country={Country}", id, country);
	}

	/// <inheritdoc />
	public async Task UpdatePrivilegesAsync(int id, UserPrivileges privilege,
		CancellationToken cancellationToken = default)
	{
		await SqliteInstrumentation.RecordAsync("user.privileges.update", async () =>
		{
			await using var connection = Connect();
			await connection.ExecuteAsync(
				"UPDATE Users SET Privilege = @Privilege WHERE Id = @Id",
				new { Id = id, Privilege = (int)privilege });
			logger.LogDebug("User row updated: Id={Id} Privilege={Privilege}", id, privilege);
		});
	}

	/// <inheritdoc />
	public async Task UpdateNameAsync(int id, string name, CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		await connection.ExecuteAsync(
			"UPDATE Users SET Name = @Name WHERE Id = @Id",
			new { Id = id, Name = name });
		logger.LogDebug("User row updated: Id={Id} Name={Name}", id, name);
	}

	/// <inheritdoc />
	public async Task UpdateSilenceEndAsync(int id, DateTimeOffset? silenceEnd,
		CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		await connection.ExecuteAsync(
			"UPDATE Users SET SilenceEnd = @SilenceEnd WHERE Id = @Id",
			new { Id = id, SilenceEnd = silenceEnd?.UtcDateTime });
		logger.LogDebug("User row updated: Id={Id} SilenceEnd={SilenceEnd}", id, silenceEnd);
	}

	/// <inheritdoc />
	/// <remarks>
	///     The safe form of the name is generated by the database itself, matching
	///     <see cref="User.MakeSafeName" />. When <paramref name="privilege" /> is
	///     <see langword="null" />, the row defaults to the unrestricted, verified, and supporter
	///     flags. A duplicate display or safe name trips a constraint violation, which is swallowed
	///     and reported as <see langword="null" />. The insert and the id read-back are one batched
	///     statement, and the new row is then re-read and returned.
	/// </remarks>
	public async Task<User?> CreateAsync(string name, string pwBcrypt, Country country,
		UserPrivileges? privilege = null,
		CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		int id;
		try
		{
			id = await connection.ExecuteScalarAsync<int>(
				"""
				INSERT INTO Users (Name, PwBcrypt, Country, Privilege)
				VALUES (@Name, @PwBcrypt, @Country, @Privilege);
				SELECT last_insert_rowid();
				""",
				new
				{
					Name = name,
					PwBcrypt = pwBcrypt,
					Country = country.ToAcronym(),
					Privilege = (int)(privilege ?? UserPrivileges.Unrestricted | UserPrivileges.Verified |
						UserPrivileges.Supporter)
				});
		}
		catch (SqliteException ex) when (ex.SqliteErrorCode == 19) // SQLITE_CONSTRAINT (Name/SafeName UNIQUE)
		{
			return null;
		}

		logger.LogDebug("User row created: Id={Id} Name={Name}", id, name);
		return (await FetchByIdAsync(id, cancellationToken))!;
	}

	/// <inheritdoc />
	public async Task SoftDeleteAsync(int id, DateTimeOffset deletedAt, CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		await connection.ExecuteAsync(
			"UPDATE Users SET DeletedAt = @DeletedAt WHERE Id = @Id",
			new { Id = id, DeletedAt = deletedAt.UtcDateTime });
		logger.LogDebug("User row soft-deleted: Id={Id} DeletedAt={DeletedAt}", id, deletedAt);
	}

	/// <inheritdoc />
	public async Task<IReadOnlyList<User>> FetchAllAsync(CancellationToken cancellationToken = default)
	{
		await using var connection = Connect();
		var rows = await connection.QueryAsync<UserRow>("SELECT * FROM Users ORDER BY Id");
		return [.. rows.Select(r => r.ToUser())];
	}

	/// <inheritdoc />
	public async Task<IReadOnlyList<User>> SearchAsync(UserSearchFilters filters, int offset, int amount,
		CancellationToken cancellationToken = default)
	{
		var whereClause = BuildSearchWhereClause(filters, out var parameters);
		parameters.Add("Offset", offset);
		parameters.Add("Amount", amount);

		await using var connection = Connect();
		var rows = await connection.QueryAsync<UserRow>(
			$"""
			 SELECT * FROM Users
			 {whereClause}
			 ORDER BY Id LIMIT @Amount OFFSET @Offset
			 """,
			parameters);
		return [.. rows.Select(r => r.ToUser())];
	}

	/// <inheritdoc />
	public async Task<int> SearchCountAsync(UserSearchFilters filters, CancellationToken cancellationToken = default)
	{
		var whereClause = BuildSearchWhereClause(filters, out var parameters);

		await using var connection = Connect();
		return await connection.ExecuteScalarAsync<int>(
			$"SELECT COUNT(*) FROM Users {whereClause}",
			parameters);
	}

	/// <summary>
	///     Builds the shared `WHERE` clause and parameters for a user search, from the same filters
	///     <see cref="SearchAsync" /> and <see cref="SearchCountAsync" /> both translate.
	/// </summary>
	/// <remarks>
	///     A numeric <see cref="UserSearchFilters.Keywords" /> matches either the id exactly or a
	///     username substring -- osu! ids and usernames are drawn from different characters, so both
	///     can be checked without ambiguity.
	/// </remarks>
	private static string BuildSearchWhereClause(UserSearchFilters filters, out DynamicParameters parameters)
	{
		var conditions = new List<string>();
		parameters = new DynamicParameters();

		if (!filters.IncludeDeleted) conditions.Add("DeletedAt IS NULL");

		if (filters.Keywords is not null)
		{
			parameters.Add("Query", $"%{User.MakeSafeName(filters.Keywords)}%");
			if (int.TryParse(filters.Keywords, out var id))
			{
				conditions.Add("(SafeName LIKE @Query OR Id = @Id)");
				parameters.Add("Id", id);
			}
			else
			{
				conditions.Add("SafeName LIKE @Query");
			}
		}

		if (filters.Countries is { Count: > 0 })
		{
			conditions.Add("Country IN @Countries");
			parameters.Add("Countries", filters.Countries.Select(c => c.ToAcronym()).ToList());
		}

		if (filters.Privilege is not null)
		{
			conditions.Add("(Privilege & @Privilege) = @Privilege");
			parameters.Add("Privilege", (int)filters.Privilege.Value);
		}

		if (filters.Silenced is not null)
		{
			conditions.Add(filters.Silenced.Value
				? "SilenceEnd > datetime('now')"
				: "(SilenceEnd IS NULL OR SilenceEnd <= datetime('now'))");
		}

		return conditions.Count == 0 ? "" : $"WHERE {string.Join(" AND ", conditions)}";
	}

	/// <summary>Creates a new SQLite connection using the repository's connection string.</summary>
	private SqliteConnection Connect()
	{
		return SqliteConnectionFactory.Open(connectionString);
	}

	/// <summary>
	///     A mutable row DTO matching the Users table columns.
	/// </summary>
	private sealed class UserRow
	{
		public int Id { get; set; }
		public string Name { get; set; } = "";
		public string SafeName { get; set; } = "";
		public int Privilege { get; set; }
		public string Country { get; set; } = "";
		public DateTime? SilenceEnd { get; set; }
		public DateTime? DeletedAt { get; set; }

		/// <summary>Builds a <see cref="User" /> from this row.</summary>
		/// <returns>The domain user.</returns>
		/// <remarks>
		///     The stored country acronym is parsed back to a <see cref="Country" /> value, falling
		///     back to <see cref="Country.Xx" /> when unrecognized, and the silence-end and deletion
		///     times are reinterpreted as UTC before being exposed as offsets.
		/// </remarks>
		public User ToUser()
		{
			var country = Enum.TryParse<Country>(Country, true, out var parsed)
				? parsed
				: Domain.Login.Country.Xx;
			return new User(Id, Name, country, (UserPrivileges)Privilege,
				SilenceEnd is { } silenceEnd
					? new DateTimeOffset(DateTime.SpecifyKind(silenceEnd, DateTimeKind.Utc))
					: null,
				DeletedAt is { } deletedAt
					? new DateTimeOffset(DateTime.SpecifyKind(deletedAt, DateTimeKind.Utc))
					: null);
		}
	}
}